// Generated by CoffeeScript 1.10.0
(function() {
  ({
    command: 'curl -s "https://www.reddit.com/r/news/.rss"',
    refreshFrequency: 300000,
    render: function(output) {
      return "<div id=\"heading\">News</div>\n<div id=\"title\"></div>\n<div id=\"link\"><a href=\"\">ClickMe</a></div>\n<div id=\"footer\"></div>";
    },
    update: function(output, domEl) {
      var $xml, dom, theItem, xml;
      dom = $(domEl);
      xml = jQuery.parseXML(output);
      $xml = $(xml);
      theItem = $xml.find('rss').find('channel').find('item');
      window.todaysNewsMaxStories = theItem.find('title').length;
      window.todaysNewsCurrentStory = 0;
      this.showStory(theItem, dom, window);
      clearInterval(window.todaysNewsInterval);
      return window.todaysNewsInterval = setInterval(((function(_this) {
        return function() {
          return _this.showStory(theItem, dom, window);
        };
      })(this)), 10000);
    },
    showStory: function(theItem, dom, win) {
      var theDate, theLink, theTitle;
      win.todaysNewsCurrentStory += 1;
      if (win.todaysNewsCurrentStory > win.todaysNewsMaxStories) {
        win.todaysNewsCurrentStory = 0;
      }
      theTitle = theItem.find('title')[win.todaysNewsCurrentStory].childNodes[0].data.split(':');
      theLink = theItem.find('link')[win.todaysNewsCurrentStory];
      theDate = theItem.find('pubDate')[win.todaysNewsCurrentStory].childNodes[0].data;
      theDate = new Date(theDate);
      dom.find(title).html(theTitle);
      return dom.find(footer).html(theDate + '   (Story ' + win.todaysNewsCurrentStory + ' of ' + win.todaysNewsMaxStories + ')');
    },
    style: "top: 300px\nright: 8px\nwidth:360px\nmargin:0px\npadding:0px\nbackground:rgba(#FFF, 0.5)\nborder:2px solid rgba(#000, 0.5)\nborder-radius:10px\noverflow:hidden\n\n#heading\n  margin:12pt\n  margin-bottom:0\n  font-family: Helvetica\n  font-size: 42pt\n  font-weight:bold\n  color: rgba(#FFF, 0.75)\n\n#title\n  margin-left:12pt\n  margin-right:12pt\n  xxmargin-bottom:-10pt\n  font-family: American Typewriter\n  font-size: 20pt\n  font-weight:bold\n\n#description\n  margin-left:12pt\n  margin-right:12pt\n  font-family: American Typewriter\n  font-size: 12pt\n  line-height:18pt\n  max-height:120pt\n  overflow:hidden\n  hyphens: auto\n\n#link\n  margin-left:12pt\n  margin-right:12pt\n  font-family: American Typewriter\n  font-size: 12pt\n  line-height:18pt\n  max-height:120pt\n  overflow:hidden\n  hyphens: auto\n  \n#footer\n  font-family: Helvetica\n  font-size: 9pt\n  margin:12pt\n  color: rgba(#000, 0.5)"
  });

}).call(this);

//# sourceMappingURL=TodaysNews.js.map
